
# Disabling automatic updates by modifying auto-update file(20auto-upgrades)
- name : Disabling automatic updates
  hosts : all
  become : yes
  become_user : cloud_user 
  tasks: 
       - name : disabling automatic updatest (part 1 ) 
         ansible.builtin.lineinfile: 
           path : /etc/apt/apt.conf.d/20auto-upgrades
           search_string: 'APT::Periodic::Unattended-Upgrade "1";'
           line: APT::Periodic::Unattended-Upgrade "0";
       - name : disabling automatic update (part 2 ) 
         ansible.builtin.lineinfile : 
          path : /etc/apt/apt.conf.d/20auto-upgrades
          search_string: 'APT::Periodic::Update-Package-Lists "1";'
          line : APT::Periodic::Update-Package-Lists "0";
